import type { Planet, SimulationConfig } from "@/lib/types";

export const fallbackSimulationConfig: SimulationConfig = {
  timeScale: 8,
  gravitationalConstant: 6.6743e-11,
  galacticSpeed: 0.08,
  gravityScale: 1,
  backendDriven: false,
  nBodyEnabled: false,
  showOrbits: true,
  paused: false
};

export function mergeSimulationConfig(config: Partial<SimulationConfig> | undefined) {
  return { ...fallbackSimulationConfig, ...config };
}

export const fallbackPlanets: Planet[] = [
  {
    name: "Mercury",
    radius: 0.383,
    displayRadius: 0.34,
    orbitRadius: 5.8,
    semiMajorAxisAu: 0.387,
    eccentricity: 0.2056,
    inclination: 7.005,
    longitudeOfAscendingNode: 48.331,
    argumentOfPeriapsis: 29.124,
    phase: 12,
    orbitSpeed: 4.0923,
    siderealPeriodDays: 87.969,
    rotationSpeed: 0.01705,
    rotationPeriodHours: 1407.6,
    axialTilt: 0.034,
    mass: 3.3011e23,
    color: "#9f978d",
    textureUrl: "/textures/2k_mercury.jpg",
    hasRings: false,
    moonCount: 0,
    featuredMoons: [],
    orbitalVelocityKmS: 47.36,
    description: "Mercury is the smallest planet and the closest world to the Sun. It has no atmosphere thick enough to soften impacts, so its surface is heavily cratered and scarred by long cliffs formed as the planet cooled and contracted. Its day is strangely long compared with its year, and its elliptical orbit makes its changing speed easy to notice in the simulation."
  },
  {
    name: "Venus",
    radius: 0.949,
    displayRadius: 0.58,
    orbitRadius: 7.7,
    semiMajorAxisAu: 0.723,
    eccentricity: 0.0068,
    inclination: 3.3947,
    longitudeOfAscendingNode: 76.68,
    argumentOfPeriapsis: 54.884,
    phase: 148,
    orbitSpeed: 1.6021,
    siderealPeriodDays: 224.701,
    rotationSpeed: -0.00412,
    rotationPeriodHours: -5832.5,
    axialTilt: 177.36,
    mass: 4.8675e24,
    color: "#d8b36b",
    textureUrl: "/textures/2k_venus_surface.jpg",
    hasRings: false,
    moonCount: 0,
    featuredMoons: [],
    orbitalVelocityKmS: 35.02,
    description: "Venus is almost Earth-sized, but its dense carbon dioxide atmosphere traps heat so strongly that the surface is hotter than Mercury. It rotates backward compared with most planets and turns so slowly that a Venus day lasts longer than a Venus year. The visual surface texture represents the rocky terrain below the permanent cloud deck."
  },
  {
    name: "Earth",
    radius: 1,
    displayRadius: 0.62,
    orbitRadius: 10,
    semiMajorAxisAu: 1,
    eccentricity: 0.0167,
    inclination: 0,
    longitudeOfAscendingNode: 0,
    argumentOfPeriapsis: 102.937,
    phase: 263,
    orbitSpeed: 0.9856,
    siderealPeriodDays: 365.256,
    rotationSpeed: 1.0027,
    rotationPeriodHours: 23.934,
    axialTilt: 23.44,
    mass: 5.97237e24,
    color: "#5aa6d6",
    textureUrl: "/textures/2k_earth_daymap.jpg",
    hasRings: false,
    moonCount: 1,
    featuredMoons: ["Moon"],
    orbitalVelocityKmS: 29.78,
    description: "Earth is the reference planet for this simulation: one astronomical unit from the Sun, with liquid oceans, a protective atmosphere, and one large Moon that stabilizes its axial tilt. Its blue-white appearance comes from water, clouds, and reflected sunlight, while the day-night rhythm is driven by a nearly 24-hour rotation."
  },
  {
    name: "Mars",
    radius: 0.532,
    displayRadius: 0.46,
    orbitRadius: 13.1,
    semiMajorAxisAu: 1.524,
    eccentricity: 0.0934,
    inclination: 1.85,
    longitudeOfAscendingNode: 49.558,
    argumentOfPeriapsis: 286.502,
    phase: 316,
    orbitSpeed: 0.524,
    siderealPeriodDays: 686.98,
    rotationSpeed: 0.9747,
    rotationPeriodHours: 24.623,
    axialTilt: 25.19,
    mass: 6.4171e23,
    color: "#d26a45",
    textureUrl: "/textures/2k_mars.jpg",
    hasRings: false,
    moonCount: 2,
    featuredMoons: ["Phobos", "Deimos"],
    orbitalVelocityKmS: 24.07,
    description: "Mars is a cold desert world with iron-rich dust, giant volcanoes, deep canyons, polar ice caps, and two small moons. Its thin atmosphere cannot support liquid water on the surface for long today, but spacecraft data shows that rivers, lakes, and groundwater shaped parts of ancient Mars."
  },
  {
    name: "Jupiter",
    radius: 11.21,
    displayRadius: 1.62,
    orbitRadius: 19.8,
    semiMajorAxisAu: 5.203,
    eccentricity: 0.0489,
    inclination: 1.304,
    longitudeOfAscendingNode: 100.464,
    argumentOfPeriapsis: 273.867,
    phase: 26,
    orbitSpeed: 0.0831,
    siderealPeriodDays: 4332.59,
    rotationSpeed: 2.418,
    rotationPeriodHours: 9.925,
    axialTilt: 3.13,
    mass: 1.8982e27,
    color: "#d7b48a",
    textureUrl: "/textures/2k_jupiter.jpg",
    hasRings: false,
    moonCount: 101,
    featuredMoons: ["Io", "Europa", "Ganymede", "Callisto"],
    orbitalVelocityKmS: 13.07,
    description: "Jupiter is the largest planet in the Solar System, massive enough to strongly shape asteroid and comet paths. Its banded atmosphere is driven by fast rotation and powerful jet streams, while the Great Red Spot is a long-lived storm larger than Earth. The four featured Galilean moons are shown as the most prominent members of a much larger moon system."
  },
  {
    name: "Saturn",
    radius: 9.45,
    displayRadius: 1.38,
    orbitRadius: 27.8,
    semiMajorAxisAu: 9.537,
    eccentricity: 0.0565,
    inclination: 2.485,
    longitudeOfAscendingNode: 113.665,
    argumentOfPeriapsis: 339.392,
    phase: 207,
    orbitSpeed: 0.0335,
    siderealPeriodDays: 10759.22,
    rotationSpeed: 2.252,
    rotationPeriodHours: 10.656,
    axialTilt: 26.73,
    mass: 5.6834e26,
    color: "#e6d19d",
    textureUrl: "/textures/2k_saturn.jpg",
    ringTextureUrl: "/textures/2k_saturn_ring_alpha.png",
    hasRings: true,
    moonCount: 274,
    featuredMoons: ["Titan", "Enceladus", "Rhea", "Iapetus", "Dione"],
    orbitalVelocityKmS: 9.68,
    description: "Saturn is a low-density gas giant wrapped in the Solar System's most dramatic ring system. The rings are mostly water-ice particles ranging from dust grains to boulder-sized chunks, separated into bands and gaps by orbital resonances with moons. Titan and Enceladus make Saturn especially important for astrobiology and ocean-world studies."
  },
  {
    name: "Uranus",
    radius: 4.01,
    displayRadius: 0.98,
    orbitRadius: 36.2,
    semiMajorAxisAu: 19.191,
    eccentricity: 0.0457,
    inclination: 0.773,
    longitudeOfAscendingNode: 74.006,
    argumentOfPeriapsis: 96.998,
    phase: 81,
    orbitSpeed: 0.0117,
    siderealPeriodDays: 30685.4,
    rotationSpeed: -1.393,
    rotationPeriodHours: -17.24,
    axialTilt: 97.77,
    mass: 8.681e25,
    color: "#8fd5df",
    textureUrl: "/textures/2k_uranus.jpg",
    hasRings: false,
    moonCount: 28,
    featuredMoons: ["Miranda", "Ariel", "Umbriel", "Titania", "Oberon"],
    orbitalVelocityKmS: 6.8,
    description: "Uranus is an ice giant with an extreme axial tilt, so it appears to roll around the Sun on its side. Its blue-green color comes mostly from methane absorbing red light, and its faint rings and moons orbit in a tilted system that reflects the planet's unusual orientation."
  },
  {
    name: "Neptune",
    radius: 3.88,
    displayRadius: 0.96,
    orbitRadius: 44.5,
    semiMajorAxisAu: 30.07,
    eccentricity: 0.0113,
    inclination: 1.77,
    longitudeOfAscendingNode: 131.784,
    argumentOfPeriapsis: 276.336,
    phase: 244,
    orbitSpeed: 0.006,
    siderealPeriodDays: 60189,
    rotationSpeed: 1.49,
    rotationPeriodHours: 16.11,
    axialTilt: 28.32,
    mass: 1.02413e26,
    color: "#3f67df",
    textureUrl: "/textures/2k_neptune.jpg",
    hasRings: false,
    moonCount: 16,
    featuredMoons: ["Triton", "Proteus", "Nereid", "Hippocamp"],
    orbitalVelocityKmS: 5.43,
    description: "Neptune is the outermost major planet, an ice giant with supersonic winds, storm systems, and a deep blue appearance shaped by methane and atmospheric haze. Triton, its largest moon, orbits backward and may be a captured Kuiper Belt object, making Neptune's moon system especially distinctive."
  }
];
