import type { Planet, SimulationConfig } from "@/lib/types";

export const fallbackSimulationConfig: SimulationConfig = {
  timeScale: 8,
  gravitationalConstant: 6.6743e-11,
  galacticSpeed: 0.08,
  gravityScale: 1,
  backendDriven: false,
  nBodyEnabled: false,
  showOrbits: true,
  paused: false
};

export function mergeSimulationConfig(config: Partial<SimulationConfig> | undefined) {
  return { ...fallbackSimulationConfig, ...config };
}

export const fallbackPlanets: Planet[] = [
  {
    name: "Mercury",
    radius: 0.383,
    displayRadius: 0.34,
    orbitRadius: 5.8,
    semiMajorAxisAu: 0.387,
    eccentricity: 0.2056,
    inclination: 7.005,
    longitudeOfAscendingNode: 48.331,
    argumentOfPeriapsis: 29.124,
    phase: 12,
    orbitSpeed: 4.0923,
    siderealPeriodDays: 87.969,
    rotationSpeed: 0.01705,
    rotationPeriodHours: 1407.6,
    axialTilt: 0.034,
    mass: 3.3011e23,
    color: "#9f978d",
    textureUrl: "/textures/2k_mercury.jpg",
    hasRings: false,
    moonCount: 0,
    featuredMoons: [],
    orbitalVelocityKmS: 47.36,
    description: "Small, iron-rich inner planet with the most eccentric orbit in this model."
  },
  {
    name: "Venus",
    radius: 0.949,
    displayRadius: 0.58,
    orbitRadius: 7.7,
    semiMajorAxisAu: 0.723,
    eccentricity: 0.0068,
    inclination: 3.3947,
    longitudeOfAscendingNode: 76.68,
    argumentOfPeriapsis: 54.884,
    phase: 148,
    orbitSpeed: 1.6021,
    siderealPeriodDays: 224.701,
    rotationSpeed: -0.00412,
    rotationPeriodHours: -5832.5,
    axialTilt: 177.36,
    mass: 4.8675e24,
    color: "#d8b36b",
    textureUrl: "/textures/2k_venus_surface.jpg",
    hasRings: false,
    moonCount: 0,
    featuredMoons: [],
    orbitalVelocityKmS: 35.02,
    description: "A slowly rotating, retrograde world with a nearly circular orbit."
  },
  {
    name: "Earth",
    radius: 1,
    displayRadius: 0.62,
    orbitRadius: 10,
    semiMajorAxisAu: 1,
    eccentricity: 0.0167,
    inclination: 0,
    longitudeOfAscendingNode: 0,
    argumentOfPeriapsis: 102.937,
    phase: 263,
    orbitSpeed: 0.9856,
    siderealPeriodDays: 365.256,
    rotationSpeed: 1.0027,
    rotationPeriodHours: 23.934,
    axialTilt: 23.44,
    mass: 5.97237e24,
    color: "#5aa6d6",
    textureUrl: "/textures/2k_earth_daymap.jpg",
    hasRings: false,
    moonCount: 1,
    featuredMoons: ["Moon"],
    orbitalVelocityKmS: 29.78,
    description: "The reference body: one astronomical unit from the Sun with a tilted spin axis."
  },
  {
    name: "Mars",
    radius: 0.532,
    displayRadius: 0.46,
    orbitRadius: 13.1,
    semiMajorAxisAu: 1.524,
    eccentricity: 0.0934,
    inclination: 1.85,
    longitudeOfAscendingNode: 49.558,
    argumentOfPeriapsis: 286.502,
    phase: 316,
    orbitSpeed: 0.524,
    siderealPeriodDays: 686.98,
    rotationSpeed: 0.9747,
    rotationPeriodHours: 24.623,
    axialTilt: 25.19,
    mass: 6.4171e23,
    color: "#d26a45",
    textureUrl: "/textures/2k_mars.jpg",
    hasRings: false,
    moonCount: 2,
    featuredMoons: ["Phobos", "Deimos"],
    orbitalVelocityKmS: 24.07,
    description: "A dusty terrestrial planet whose eccentricity makes its speed changes easy to see."
  },
  {
    name: "Jupiter",
    radius: 11.21,
    displayRadius: 1.62,
    orbitRadius: 19.8,
    semiMajorAxisAu: 5.203,
    eccentricity: 0.0489,
    inclination: 1.304,
    longitudeOfAscendingNode: 100.464,
    argumentOfPeriapsis: 273.867,
    phase: 26,
    orbitSpeed: 0.0831,
    siderealPeriodDays: 4332.59,
    rotationSpeed: 2.418,
    rotationPeriodHours: 9.925,
    axialTilt: 3.13,
    mass: 1.8982e27,
    color: "#d7b48a",
    textureUrl: "/textures/2k_jupiter.jpg",
    hasRings: false,
    moonCount: 101,
    featuredMoons: ["Io", "Europa", "Ganymede", "Callisto"],
    orbitalVelocityKmS: 13.07,
    description: "The dominant giant planet, scaled down visually so the whole system remains navigable."
  },
  {
    name: "Saturn",
    radius: 9.45,
    displayRadius: 1.38,
    orbitRadius: 27.8,
    semiMajorAxisAu: 9.537,
    eccentricity: 0.0565,
    inclination: 2.485,
    longitudeOfAscendingNode: 113.665,
    argumentOfPeriapsis: 339.392,
    phase: 207,
    orbitSpeed: 0.0335,
    siderealPeriodDays: 10759.22,
    rotationSpeed: 2.252,
    rotationPeriodHours: 10.656,
    axialTilt: 26.73,
    mass: 5.6834e26,
    color: "#e6d19d",
    textureUrl: "/textures/2k_saturn.jpg",
    ringTextureUrl: "/textures/2k_saturn_ring_alpha.png",
    hasRings: true,
    moonCount: 274,
    featuredMoons: ["Titan", "Enceladus", "Rhea", "Iapetus", "Dione"],
    orbitalVelocityKmS: 9.68,
    description: "A low-density gas giant with a ring plane aligned to its tilted equator."
  },
  {
    name: "Uranus",
    radius: 4.01,
    displayRadius: 0.98,
    orbitRadius: 36.2,
    semiMajorAxisAu: 19.191,
    eccentricity: 0.0457,
    inclination: 0.773,
    longitudeOfAscendingNode: 74.006,
    argumentOfPeriapsis: 96.998,
    phase: 81,
    orbitSpeed: 0.0117,
    siderealPeriodDays: 30685.4,
    rotationSpeed: -1.393,
    rotationPeriodHours: -17.24,
    axialTilt: 97.77,
    mass: 8.681e25,
    color: "#8fd5df",
    textureUrl: "/textures/2k_uranus.jpg",
    hasRings: false,
    moonCount: 28,
    featuredMoons: ["Miranda", "Ariel", "Umbriel", "Titania", "Oberon"],
    orbitalVelocityKmS: 6.8,
    description: "An ice giant rolling around the Sun with an extreme axial tilt."
  },
  {
    name: "Neptune",
    radius: 3.88,
    displayRadius: 0.96,
    orbitRadius: 44.5,
    semiMajorAxisAu: 30.07,
    eccentricity: 0.0113,
    inclination: 1.77,
    longitudeOfAscendingNode: 131.784,
    argumentOfPeriapsis: 276.336,
    phase: 244,
    orbitSpeed: 0.006,
    siderealPeriodDays: 60189,
    rotationSpeed: 1.49,
    rotationPeriodHours: 16.11,
    axialTilt: 28.32,
    mass: 1.02413e26,
    color: "#3f67df",
    textureUrl: "/textures/2k_neptune.jpg",
    hasRings: false,
    moonCount: 16,
    featuredMoons: ["Triton", "Proteus", "Nereid", "Hippocamp"],
    orbitalVelocityKmS: 5.43,
    description: "The outer ice giant in this simulation, moving slowly through a slightly tilted orbit."
  }
];
